### ISSUE TITLE
Unable to locate element: [id="ap_email"]

### ISSUE THREAD

**Issue by danielkennedy74** [mkukar/GroceryGrabber#1]
Cool program, runs most of the way through, but then throws the following error:

selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="ap_email"]

**Comment by mkukar** [comment]
Hey Daniel, I cleaned up the code to both prevent this and handle similar errors a bit more gracefully. This is caused when it can't see the log in page, probably because you are already signed in when it loads it. The latest commit should fix this, and I will create a new v1.1 version that contains this fix + some extra features.

Thanks for trying this out and I hope this solves your problem! Please re-open if it pops up again.
