### ISSUE TITLE
login issues when whole foods needs to verify with OTP

### ISSUE THREAD

**Issue by banittles** [mkukar/GroceryGrabber#3]
cant get through login when whole foods asks to send a code via app or email.

**Comment by banittles** [comment]
turned off automatic login, got it running!

**Comment by mkukar** [comment]
Hi banittles, yes this sometimes happens especially after the program has been running for a while. You can either do what you did and turn of automatic login or if you start it up and wait a few seconds/minutes (it will retry the automatic login a few times), then it will give you 30 seconds to manually enter your password and solve the captcha and/or 2-factor code.

Glad it is working for you now and also please take a look at issue #2 since there is a known problem with the cart merchantIDs that could affect you!

I'll mark this as closed as I don't think I can automate the code entry or captcha, but please re-open it if you continue to have problems!
